version: '3'

services:
  fpm:
    build:
      context: ./docker/fpm
      args:
        PHP_VERSION: ${PHP_VERSION}
        PSR_VERSION: ${PSR_VERSION}
        PHALCON_VERSION: ${PHALCON_VERSION}
    restart: always
    volumes:
      - ./:/var/www/html

  nginx:
    build:
      context: ./docker/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    restart: always
    ports:
      - 80:80

  database:
    build: 
      context: ./docker/postgres
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
